### ISSUE TITLE
7z e failed to extract hfs file extension

### ISSUE THREAD

**Issue by zendzo** [notthebee/macos_usb#8]
`7z e -txar *.pkg *.dmg; 7z e *.dmg */Base*; 7z e -tdmg Base*.dmg *.hfs`

**Comment by notthebee** [comment]
Would you mind sharing the output of the command?

**Comment by Sniki** [comment]
Haven't checked or tested the script but since i see that hfs is mentioned as an extension then that is wrong.
HfsPlus.efi is the driver needed so i guess `Hfs*.efi` or something similar would fix it ?

Reference to the file as an example: https://github.com/Sniki/Lenovo-Thinkpad-X240/blob/master/EFI/OC/Drivers/HfsPlus.efi
https://github.com/Sniki/Lenovo-Thinkpad-X240/blob/master/EFI/OC/Drivers/HfsPlus.efi

**Comment by notthebee** [comment]
No response from the OP, closing
